"""Neutral workflow settings; historical config property names are normalized.

Process environment reads use only neutral names, including empty values.
Third-party credentials are never aliased.
"""
from __future__ import annotations

import os
from collections.abc import Mapping

WORKFLOW_ENV_NAMES = frozenset({
    "ALLOW_INCOMPATIBLE_VALIDATION_RECORDS",
    "ANOMALY_MAX_CASES_THRESHOLD",
    "ANOMALY_MAX_DEATHS_THRESHOLD",
    "ANOMALY_MIN_PRIOR_RECORDS",
    "ANOMALY_SPIKE_MULTIPLIER",
    "AUTHORITY_GAP_JURISDICTION_RETRY_MAX_QUERIES",
    "AUTHORITY_GAP_KNOWN_DOMAIN_RETRY_MAX_QUERIES",
    "AUTHORITY_GAP_OFFICIAL_PAGE_FAMILY_RETRY_MAX_QUERIES",
    "AUTHORITY_GAP_RETRY_ENABLED",
    "AUTHORITY_GAP_RETRY_MAX_ITERATIONS",
    "AUTHORITY_GAP_RETRY_MAX_QUERIES",
    "AUTHORITY_GAP_RETRY_RESULT_BUDGET",
    "CHROMIUM_EXECUTABLE",
    "COLLECTION_MODE",
    "CONTENT_FIXTURE_MAP_PATH",
    "DIRECT_ALLOW_GENERATED_URL_ONLY",
    "DIRECT_COLLECTION_ENABLE_AUDIT_VALIDATION",
    "DIRECT_ENABLE_TEXT_FALLBACK_AFTER_ROW_EXTRACTION",
    "DIRECT_FALLBACK_FETCH_LIMIT",
    "DIRECT_FALLBACK_LINK_FETCH_LIMIT",
    "DIRECT_FAST_STOP_ON_VERIFIED_TARGET",
    "DIRECT_MIN_TARGET_METRIC_RECORDS",
    "DISEASE_INTELLIGENCE_FALLBACK_TO_CURATED",
    "DISEASE_INTELLIGENCE_FORCE_LLM",
    "ENABLE_ITERATIVE_SOURCE_DISCOVERY",
    "ENABLE_LANGSMITH_TRACE",
    "ENABLE_LIVE_FETCH",
    "ENABLE_LIVE_SEARCH",
    "ENABLE_LLM_DISEASE_INTELLIGENCE",
    "ENABLE_LLM_EXTRACTION",
    "ENABLE_LLM_SOURCE_CREDIBILITY",
    "ENABLE_LLM_SOURCE_CRITIC",
    "ENABLE_LLM_SOURCE_IDENTITY",
    "ENABLE_LLM_SOURCE_PLANNING",
    "EVENT_LINK_EXPANSION_ENABLED",
    "EVENT_LINK_EXPANSION_LIMIT",
    "EXTERNAL_FETCH_ENABLED",
    "EXTERNAL_FETCH_PROVIDER_ORDER",
    "FETCH_ALLOWED_FINAL_ROLES",
    "FETCH_ALLOW_NEEDS_REVIEW",
    "FETCH_DOMAIN_ALLOWLIST",
    "FETCH_DOMAIN_BLOCKLIST",
    "FETCH_MAX_BYTES",
    "FETCH_MAX_NODE_SECONDS",
    "FETCH_MAX_SEARCH_DERIVED_SOURCES",
    "FETCH_MAX_TOTAL_SOURCES",
    "FETCH_MIN_CREDIBILITY_SCORE",
    "FETCH_PARSE_PDF_TEXT",
    "FETCH_PARSE_TABLES",
    "FETCH_SEARCH_DERIVED_SOURCES",
    "FETCH_STORE_RAW_TEXT",
    "FETCH_TIMEOUT_SECONDS",
    "FETCH_USER_AGENT",
    "FINAL_PACKAGE_MODE",
    "HUMAN_REVIEW_APPLY_DECISIONS",
    "HUMAN_REVIEW_DECISIONS_PATH",
    "HUMAN_REVIEW_ENABLED",
    "HUMAN_REVIEW_REQUIRE_REVIEWER_ID",
    "ITERATIVE_SEARCH_ALLOW_DETERMINISTIC_FALLBACK",
    "ITERATIVE_SEARCH_MAX_ITERATIONS",
    "ITERATIVE_SEARCH_MAX_QUERIES_PER_ITERATION",
    "ITERATIVE_SEARCH_MAX_TOTAL_QUERIES",
    "ITERATIVE_SEARCH_MAX_TOTAL_RESULTS",
    "ITERATIVE_SEARCH_REQUIRE_LLM",
    "ITERATIVE_SEARCH_REQUIRE_OBSERVATION_AFTER_EACH_ITERATION",
    "ITERATIVE_SEARCH_STOP_WHEN_LLM_SAYS_SUFFICIENT",
    "LANGFLOW_DEMO_API_BASE",
    "LANGGRAPH_STUDIO_URL",
    "LANGSMITH_APP_BASE_URL",
    "LLM_EFFORT",
    "LLM_EVENT_SOURCE_MIN_SPANS",
    "LLM_EXTRACTION_MAX_CONCURRENCY",
    "LLM_EXTRACTION_ROLLING_YIELD_WINDOW",
    "LLM_EXTRACTION_SAFETY_MAX_CALLS",
    "LLM_EXTRACTION_SCHEDULER_MODE",
    "LLM_EXTRACTION_SOFT_CHECKPOINT_CALLS",
    "LLM_FALLBACK_TO_RULE_BASED",
    "LLM_FOCUSED_RECOVERY_MAX_CALLS",
    "LLM_FOCUSED_RECOVERY_MAX_SOURCES",
    "LLM_FOCUSED_RECOVERY_RESERVED_CALLS",
    "LLM_FOCUSED_RECOVERY_SPANS_PER_SOURCE",
    "LLM_HARD_PRIMARY_CALLS",
    "LLM_HIGH_VALUE_SOURCE_MIN_SPANS",
    "LLM_MAX_CHUNKS",
    "LLM_MAX_DOMAIN_CALL_SHARE",
    "LLM_MAX_RETRIES",
    "LLM_MAX_TOKENS",
    "LLM_MODEL",
    "LLM_MUST_FETCH_MIN_CHUNKS_PER_SOURCE",
    "LLM_OFFICIAL_EXTRACTION_MAX_CHUNKS",
    "LLM_PROVIDER",
    "LLM_SOFT_PRIMARY_CALLS",
    "LLM_SOURCE_CREDIBILITY_MAX_SOURCES",
    "LLM_SOURCE_CREDIBILITY_SOURCE_ID_ALLOWLIST",
    "LLM_SOURCE_CRITIC_MAX_FAILURES",
    "LLM_SOURCE_CRITIC_MAX_NODE_SECONDS",
    "LLM_SOURCE_CRITIC_MAX_SOURCES",
    "LLM_SOURCE_CRITIC_REVIEW_BLOCKS_FETCH",
    "LLM_SOURCE_CRITIC_SOURCE_ID_ALLOWLIST",
    "LLM_SOURCE_IDENTITY_ALLOW_DETERMINISTIC_FALLBACK",
    "LLM_SOURCE_IDENTITY_MAX_SOURCES",
    "LLM_SOURCE_IDENTITY_POST_FETCH",
    "LLM_SOURCE_IDENTITY_REQUIRE_LLM",
    "LLM_STRUCTURED_OUTPUT_METHOD",
    "LLM_TEMPERATURE",
    "LLM_THINKING",
    "LLM_TIMEOUT_SECONDS",
    "METRIC_ROW_BATCH_SIZE",
    "PIPELINE_MODE",
    "RESOURCE_LINK_EXPANSION_LIMIT",
    "RUN_MODE",
    "SEARCH_COMBINE_WITH_SEED_CATALOG",
    "SEARCH_FIXTURE_PATH",
    "SEARCH_MAX_QUERIES",
    "SEARCH_MAX_RESULTS_PER_QUERY",
    "SEARCH_MAX_TOTAL_RESULTS",
    "SEARCH_MODE",
    "SEARCH_PROVIDER",
    "SEARCH_PROVIDER_CHANNEL_ALLOWLIST",
    "SEARCH_TIMEOUT_SECONDS",
    "SEED_SOURCE_OVERLAY_PATH",
    "SOURCE_ID_ALLOWLIST",
    "SOURCE_ROLE_POLICY_OVERLAY_PATH",
    "TAVILY_EXTRACT_CHUNKS_PER_SOURCE",
    "TAVILY_EXTRACT_DEPTH",
    "TAVILY_EXTRACT_FORMAT",
    "TAVILY_EXTRACT_TIMEOUT_SECONDS",
    "TESSDATA_DIR",
    "TESSERACT_EXECUTABLE",
    "TRACE_ID",
    "TRACE_RUN_NAME",
    "TRACE_SESSION_ID",
    "UNIVERSAL_SESSION_DIR",
    "USE_FIXTURE_DOCUMENTS",
    "VALIDATION_HELD_OUT_RECORDS_PATH",
    "VALIDATION_MODE",
})


def canonical_env_name(name: str) -> str:
    if name.startswith("HDC_") and name[4:] in WORKFLOW_ENV_NAMES:
        return name[4:]
    return name


def get_env(name: str, default=None):
    """Read only the neutral process environment name.

    Historical config properties may be normalized by canonical_env_name,
    but a prefixed process variable never selects a new run's settings.
    """
    return os.environ.get(canonical_env_name(name), default)


def normalize_env_updates(updates: Mapping[str, str]) -> dict[str, str]:
    """Accept older caller mappings while always emitting neutral keys."""
    normalized = {canonical_env_name(name): value for name, value in updates.items()}
    for name, value in updates.items():
        if canonical_env_name(name) == name:
            normalized[name] = value
    return normalized
